- name: Add Grafana APT repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: Add Grafana GPG key
  ansible.builtin.command: wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: latest

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
